/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.ProductDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author 张睿哲
 */
public class ProdManagementPanel extends javax.swing.JPanel {

    private JPanel parentPanel;
    private ProductDirectory dir;
    /**
     * Creates new form ProdManagementPanel
     */
    public ProdManagementPanel(JPanel p,ProductDirectory dir) {
        initComponents();
        this.parentPanel=p;
        this.dir=dir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateProd = new javax.swing.JButton();
        btnManageProd = new javax.swing.JButton();

        btnCreateProd.setText("Create Product");
        btnCreateProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProdActionPerformed(evt);
            }
        });

        btnManageProd.setText("Manage Products");
        btnManageProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnCreateProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(btnManageProd)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateProd)
                    .addComponent(btnManageProd))
                .addContainerGap(342, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProdActionPerformed
        // TODO add your handling code here:
        CreateProdPanel create=new CreateProdPanel(this.parentPanel,dir);
        this.parentPanel.add("createProductPanel",create);
        CardLayout layout=(CardLayout)this.parentPanel.getLayout();
        layout.next(this.parentPanel);
    }//GEN-LAST:event_btnCreateProdActionPerformed

    private void btnManageProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProdActionPerformed
        // TODO add your handling code here:
        ManageProdPanel manage=new ManageProdPanel(this.parentPanel,dir);
        this.parentPanel.add("manageProductPanel",manage);
        CardLayout layout=(CardLayout)this.parentPanel.getLayout();
        layout.show(this.parentPanel, "manageProductPanel");
        
    }//GEN-LAST:event_btnManageProdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateProd;
    private javax.swing.JButton btnManageProd;
    // End of variables declaration//GEN-END:variables
}
